P8105_hw1 building block
================

Author: Minghui Wang, mw3743<br> Date: 2024-09-12

The purpose of this file is to complete the questions in [howework
1](https://p8105.com/homework_1.html).

# Problem 1

## Describe the `penguins` dataset

### Use of inline R code

``` r
# Input data
data("penguins", package = "palmerpenguins")

# Acquire the data in this dataset, including names / values of important variables
summary(penguins)
```

    ##       species          island    bill_length_mm  bill_depth_mm  
    ##  Adelie   :152   Biscoe   :168   Min.   :32.10   Min.   :13.10  
    ##  Chinstrap: 68   Dream    :124   1st Qu.:39.23   1st Qu.:15.60  
    ##  Gentoo   :124   Torgersen: 52   Median :44.45   Median :17.30  
    ##                                  Mean   :43.92   Mean   :17.15  
    ##                                  3rd Qu.:48.50   3rd Qu.:18.70  
    ##                                  Max.   :59.60   Max.   :21.50  
    ##                                  NA's   :2       NA's   :2      
    ##  flipper_length_mm  body_mass_g       sex           year     
    ##  Min.   :172.0     Min.   :2700   female:165   Min.   :2007  
    ##  1st Qu.:190.0     1st Qu.:3550   male  :168   1st Qu.:2007  
    ##  Median :197.0     Median :4050   NA's  : 11   Median :2008  
    ##  Mean   :200.9     Mean   :4202                Mean   :2008  
    ##  3rd Qu.:213.0     3rd Qu.:4750                3rd Qu.:2009  
    ##  Max.   :231.0     Max.   :6300                Max.   :2009  
    ##  NA's   :2         NA's   :2

``` r
# Acquire the size of the dataset (using nrow and ncol)
nrow(penguins)
```

    ## [1] 344

``` r
ncol(penguins)
```

    ## [1] 8

``` r
# Acquire the mean flipper length
mean(penguins$flipper_length_mm, na.rm = TRUE)
```

    ## [1] 200.9152

### Description of the `penguins` dataset

The penguins dataset consists of 344 rows and 8 columns. It contains
data from penguins of three species, which are Adelie, Chinstrap, and
Gentoo. Some important variables in the data are species, island(Biscoe,
Dream, or Torgersen), bill_length_mm, bill_depth_mm, flipper_length_mm,
body_mass_g, sex, year. The size of the penguins dataset is 344 rows and
8 columns. Additionally, the mean flipper length in the dataset is
200.92 mm.

## Make scatterplot

# Problem 2

## Create data frame

## Take mean of each variable
